### ISSUE TITLE
Failure when building the libs

### ISSUE THREAD

**Issue by Irvise** [RREE/build-avr-ada-toolchain#6]
I am trying to build the toolchain. Everything goes pretty smooth up until the last step, when the libraries need to be build.

The problem is that the version that comes by default int versions.inc is 1.9.0. However, version 1.2.2 is hardcoded to be downloaded. But, it is not downloaded since it is not in the download script.

In order to overcome this issue I copied the master branch of sourceforge into the build directory and renamend so that it would be detected by the build script. Just as the build starts it fails with a warning that gnatmake is deprecated and gprbuild should be used instead. I changed gnatmake from the build scripts with the hopes that it would work but still fails since it seams like gprbuild does not like what it is reading (are they very old build scripts?).

I tried this time to go with the tagged version in SF avr-libs-1.2.2, however, the same problem occurs regarding gnatmake.

Is this an issue or am I doing something wrong?

**Comment by RREE** [comment]
Am 18.04.2020 um 11:36 schrieb Irvise:
> I am trying to build the toolchain. Everything goes pretty smooth up
> until the last step, when the libraries need to be build.

The build script is for the tool chain only, not for the actual AVR-Ada
library.

> The problem is that the version that comes by default int versions.inc
> is 1.9.0. However, version 1.2.2 is hardcoded to be downloaded. But, it
> is not downloaded since it is not in the download script.

I intended to release a new version 2.0 of AVR-Ada without the
infrastructure for building the tool chain, but that never happened.

> In order to overcome this issue I copied the master branch of
> sourceforge into the build directory and renamend so that it would be
> detected by the build script.

That is the correct way now.

> Just as the build starts it fails with a
> warning that gnatmake is deprecated and gprbuild should be used instead.

Both should do it.

> I changed gnatmake from the build scripts with the hopes that it would
> work but still fails since it seams like gprbuild does not like what it
> is reading (are they very old build scripts?).

Yes and no, the gpr files are old, but the syntax didn't change. I still
use avr-gnatmake for the libraries. avr-gnatmake is built as part of the
toolchain.

> I tried this time to go with the tagged version in SF avr-libs-1.2.2,
> however, the same problem occurs regarding gnatmake.

Please checkout the latest version from SF.

> Is this an issue or am I doing something wrong?

As it works for me, there must be missing some doc how to use it.
1. Put the newly built toolchain in your PATH,
2. go into the freshly updated copy of AVR-Ada
3. run ./configure to update or create ./config
4. go into AVR-Ada/avr
5. run "make | tee make_lib.log" and send me the output make_lib.log

regards
    Rolf

**Comment by Irvise** [comment]
Thanks for the quick reply @RREE.

I did what you said (building the libs in a stand alone fashion) and they build perfectly.

However, there is another issue. In the [introductory section of the wiki](https://sourceforge.net/p/avr-ada/wiki/Introductory%20Tutorial/) it says there is a Makefile that should be installed with the examples. I have searched and greped my way through, but there are no examples installed by the avr-libs package. Is the directory apps which contains several programs (and the examples folder) supposed to be installed or is it meant to stay where the source is?

I copied the Makefile from the examples program, tweaked it as per instructions and now I have a blinking led. I must say I am quite happy.

Just one note. The instructions of installation in SF lead the reader to think that the build script will also build the libraries. It may be better to clarify that it only builds the tooling and that a git clone, configure, make, make install should come next. Therefore, the variable `build_avrada="yes"` in your build script should be set to no. And that the examples should be taken from the cloned repo and not from the installation directory.

In any case. Thank you very much. If you need some more feedback, please, do ask.

Regards,
Fernando Oleo
